#! /bin/bash
rm -f *in *out*
echo " parameter optimization tests (AE) except popt(mo+ci) ..."

for i in varmin eminlin eminlm eminsnr eminpopt
do
  cp ../../templates/$i.in .
  $AMOLQCRUN $i

  R=`grep "total energy" $i.$REF|tail -n 1|awk {'print $4;'}`
  C=`grep "total energy" $i.out|tail -n 1|awk {'print $6;'}`
  if [ $R == $C ] ; then
     echo -e "    $i optimization test \033[32mpassed.\033[39m"
     rm -f $i.in $i.out fort*
  else
     export FAILED=1
     echo -e "    $i optimization test \033[31mfailed.\033[39m"
     echo "    Check $PWD/$i.out for more information."
  fi
done
