macro(get_subdirectories subdirs directory)
    file(GLOB pot_subdirs RELATIVE ${directory} ${directory}/*)
    set(dirlist "")
    foreach(pot_subdir ${pot_subdirs})
        if(IS_DIRECTORY ${directory}/${pot_subdir})
            list(APPEND dirlist ${pot_subdir})
        endif()
    endforeach()
    set(${subdirs} ${dirlist})
endmacro()
