#! /bin/bash
rm -f *in *out*
echo " ECP wavefunction tests ..."
for i in sm3-ECP sm444-ECP cas44-ECP
do
  cp ../../templates/JASECP.in $i.in
  $SED -i "s/XXX/C2-$i/" $i.in
  $AMOLQCRUN $i

  R=`grep "total energy" $i.$REF|tail -n 1|awk {'print $4;'}`
  C=`grep "total energy" $i.out|tail -n 1|awk {'print $6;'}`
  if [ $R == $C ] ; then
    echo -e "    $i ECP wavefunction test \033[32mpassed.\033[39m"
    rm -f $i.in $i.out
  else
    export FAILED=1
    echo -e "    $i ECP wavefunction test \033[31mfailed.\033[39m"
    echo "    Check $PWD/$i.out for more information."
  fi
done

